target-version = "py312"
line-length = 100

[lint]
select = [
  "E",   # pycodestyle errors
  "F",   # pyflakes
  "I",   # import sorting
  "B",   # bugbear
  "UP",  # pyupgrade
]
ignore = []

[format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
